name: Notify Slack of New Deployment

on:
  # Will trigger this workflow when a new deployment is created
  deployment:

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      # Sends slack message to a channel
      - name: Send Slack Message
        uses: archive/github-actions-slack@v2.7.0
        with:
          slack-bot-user-oauth-access-token: 
          ${{ secrets.SLACK_BOT_USER_ACCESS_TOKEN }}
          slack-channel: ${{ vars.SLACK_CHANNEL }}
          slack-text: |
            Hi there üëãüèª

            A new deployment has been created in the ${{ github.repository }} /
            repository on the `${{ github.ref }}` branch/tag \
            (SHA: `${{ github.sha }}`).
